# Generated by Django 5.2.6 on 2025-09-21 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do pet')),
                ('especie', models.CharField(choices=[('Cão', 'Cão'), ('Gato', 'Gato'), ('Outro', 'Outro')], max_length=10, verbose_name='Espécie')),
                ('porte', models.CharField(choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande')], max_length=10, verbose_name='Porte')),
                ('sexo', models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=10, verbose_name='Sexo')),
                ('idade_meses', models.PositiveIntegerField(help_text='Idade aproximada em meses', verbose_name='Idade (meses)')),
                ('descricao', models.TextField(help_text='Descrição geral do pet', verbose_name='Descrição')),
                ('historia', models.TextField(blank=True, help_text='História do pet, como foi resgatado, etc.', null=True, verbose_name='História')),
                ('informacoes_saude', models.TextField(blank=True, help_text='Vacinas, castração, problemas de saúde, etc.', null=True, verbose_name='Informações de saúde')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('status_anuncio', models.CharField(choices=[('Pendente', 'Pendente de Moderação'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=20, verbose_name='Status do anúncio')),
                ('status_adocao', models.CharField(choices=[('Disponível', 'Disponível'), ('Em Processo', 'Em Processo'), ('Adotado', 'Adotado')], default='Disponível', max_length=20, verbose_name='Status da adoção')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('motivo_rejeicao', models.TextField(blank=True, null=True, verbose_name='Motivo da rejeição')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_doados', to=settings.AUTH_USER_MODEL, verbose_name='Doador')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'db_table': 'pet',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='FotoPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='pets/fotos/', verbose_name='Imagem')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição da foto')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição das fotos', verbose_name='Ordem')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do upload')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='pets.pet', verbose_name='Pet')),
            ],
            options={
                'verbose_name': 'Foto do Pet',
                'verbose_name_plural': 'Fotos dos Pets',
                'db_table': 'foto_pet',
                'ordering': ['ordem', 'data_upload'],
            },
        ),
        migrations.CreateModel(
            name='CandidaturaAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respostas_formulario', models.JSONField(help_text='Respostas do candidato no formulário de adoção', verbose_name='Respostas do formulário')),
                ('status', models.CharField(choices=[('Enviada', 'Enviada'), ('Visualizada', 'Visualizada'), ('Respondida', 'Respondida')], default='Enviada', max_length=20, verbose_name='Status')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de visualização')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data da resposta')),
                ('observacoes_doador', models.TextField(blank=True, null=True, verbose_name='Observações do doador')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to=settings.AUTH_USER_MODEL, verbose_name='Candidato')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='pets.pet', verbose_name='Pet')),
            ],
            options={
                'verbose_name': 'Candidatura de Adoção',
                'verbose_name_plural': 'Candidaturas de Adoção',
                'db_table': 'candidatura_adocao',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.AddConstraint(
            model_name='candidaturaadocao',
            constraint=models.UniqueConstraint(fields=('pet', 'candidato'), name='unique_candidatura_per_pet'),
        ),
    ]
