# Generated by Django 5.2.6 on 2025-09-24 03:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidaturaadocao',
            name='unique_candidatura_per_pet',
        ),
        migrations.AlterUniqueTogether(
            name='candidaturaadocao',
            unique_together={('pet', 'candidato')},
        ),
    ]
