# Generated by Django 5.2.6 on 2025-09-21 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoChatIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da configuração')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Configuração Chat IA',
                'verbose_name_plural': 'Configurações Chat IA',
                'db_table': 'configuracao_chat_ia',
            },
        ),
        migrations.CreateModel(
            name='InteracaoChatIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_usuario', models.TextField(verbose_name='Mensagem do usuário')),
                ('resposta_ia', models.TextField(verbose_name='Resposta da IA')),
                ('contexto', models.CharField(choices=[('BuscaPet', 'Busca de Pet'), ('DuvidaAdocao', 'Dúvida sobre Adoção'), ('CuidadosPet', 'Cuidados com Pet'), ('SuporteTecnico', 'Suporte Técnico'), ('SugestaoPet', 'Sugestão de Pet'), ('InformacaoGeral', 'Informação Geral')], max_length=20, verbose_name='Contexto da interação')),
                ('data_interacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da interação')),
                ('tempo_resposta_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo de resposta (ms)')),
                ('feedback_positivo', models.BooleanField(blank=True, help_text='Se o usuário avaliou a resposta como útil', null=True, verbose_name='Feedback positivo')),
                ('sessao_id', models.CharField(blank=True, help_text='Identificador da sessão de chat', max_length=100, null=True, verbose_name='ID da sessão')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes_chat', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Interação Chat IA',
                'verbose_name_plural': 'Interações Chat IA',
                'db_table': 'interacao_chat_ia',
                'ordering': ['-data_interacao'],
            },
        ),
    ]
